name: General Testing

on:
  workflow_dispatch:
    inputs:
      testID:
        required: true
        default: "no test"
        type: string

jobs:
    runTest:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/labeler@v4
        - name: Setup g++
          run: sudo apt-get install -y g++
        - name: Compile
          run: make ex02
        - name: run test1
          run: |
            ./C++/ex${{ inputs.testID }}/ex${{ inputs.testID }}.exe < testingFiles/C++/ex${{ inputs.testID }}/ex${{ inputs.testID }}.input1.txt > ${{ runner.temp }}/ex${{ inputs.testID }}.output1.txt
            diff ${{ runner.temp }}/ex${{ inputs.testID }}.output1.txt testingFiles/C++/ex${{ inputs.testID }}/CorrectOutput/ex${{ inputs.testID }}.correct.output1.txt