name: C++ Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ex01a:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install g++
      run: sudo apt-get install -y g++
    - name: make ex01a
      run: make all
    - name: run file
      run: ./C++/ex01a/ex01a.exe < testingFiles/C++/ex01a/ex01a.input1.txt > ${{ runner.temp }}/ex01a.output1.txt
    - name: compare results
      run: diff ${{ runner.temp }}/ex01a.output1.txt testingFiles/C++/ex01a/CorrectOutput/ex01a.correct.output1.txt

  ex02:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup g++
      run: sudo apt-get install -y g++
    - name: Compile
      run: make ex02
    - name: run test1
      run: |
        ./C++/ex02/ex02.exe < testingFiles/C++/ex02/ex02.input1.txt > ${{ runner.temp }}/ex02.output1.txt
        diff ${{ runner.temp }}/ex02.output1.txt testingFiles/C++/ex02/CorrectOutput/ex02.correct.output1.txt
    - name: run test2
      run: |
        ./C++/ex02/ex02.exe < testingFiles/C++/ex02/ex02.input2.txt > ${{ runner.temp }}/ex02.output2.txt
        diff ${{ runner.temp }}/ex02.output2.txt testingFiles/C++/ex02/CorrectOutput/ex02.correct.output2.txt
  ex03:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup g++
      run: sudo apt-get install -y g++
    - name: Compile
      run: make ex03
    - name: run test1
      run: |
        ./C++/ex03/ex03.exe < testingFiles/C++/ex03/ex03.input1.txt > ${{ runner.temp }}/ex03.output1.txt
        diff ${{ runner.temp }}/ex03.output1.txt testingFiles/C++/ex03/CorrectOutput/ex03.correct.output1.txt
    - name: run test2
      run: |
        ./C++/ex03/ex03.exe < testingFiles/C++/ex03/ex03.input2.txt > ${{ runner.temp }}/ex03.output2.txt
        diff ${{ runner.temp }}/ex03.output2.txt testingFiles/C++/ex03/CorrectOutput/ex03.correct.output2.txt
    - name: run test3
      run: |
        ./C++/ex03/ex03.exe < testingFiles/C++/ex03/ex03.input3.txt > ${{ runner.temp }}/ex03.output3.txt
        diff ${{ runner.temp }}/ex03.output3.txt testingFiles/C++/ex03/CorrectOutput/ex03.correct.output3.txt
