name: C++ Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ex01:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install g++
      run: sudo apt-get install -y g++
    - name: make ex01
      run: make all
    - name: run file
      run: ./C++/ex01/ex01.exe < ${{ runner.temp }}/ex01.output1.txt
    - name: compare results
      run: diff ${{ runner.temp }}/ex01.output1.txt testingFiles/C++/ex01/CorrectOutput/ex01.correct.output1.txt

  ex02:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup g++
      run: sudo apt-get install -y g++
    - name: Compile
      run: make ex02
    - name: run test1
      run: |
        ./C++/ex02/ex02.exe < testingFiles/C++/ex02/ex02.input1.txt > ${{ runner.temp }}/ex02.output1.txt
        diff ${{ runner.temp }}/ex02.output1.txt testingFiles/C++/ex02/CorrectOutput/ex02.correct.output1.txt
    - name: run test2
      run: |
        ./C++/ex02/ex02.exe < testingFiles/C++/ex02/ex02.input2.txt > ${{ runner.temp }}/ex02.output2.txt
        diff ${{ runner.temp }}/ex02.output2.txt testingFiles/C++/ex02/CorrectOutput/ex02.correct.output2.txt
  ex03:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup g++
      run: sudo apt-get install -y g++
    - name: Compile
      run: make ex03
    - name: run test1
      run: |
        ./C++/ex03/ex03.exe < testingFiles/C++/ex03/ex03.input1.txt > ${{ runner.temp }}/ex03.output1.txt
        diff ${{ runner.temp }}/ex03.output1.txt testingFiles/C++/ex03/CorrectOutput/ex03.correct.output1.txt
    - name: run test2
      run: |
        ./C++/ex03/ex03.exe < testingFiles/C++/ex03/ex03.input2.txt > ${{ runner.temp }}/ex03.output2.txt
        diff ${{ runner.temp }}/ex03.output2.txt testingFiles/C++/ex03/CorrectOutput/ex03.correct.output2.txt
    - name: run test3
      run: |
        ./C++/ex03/ex03.exe < testingFiles/C++/ex03/ex03.input3.txt > ${{ runner.temp }}/ex03.output3.txt
        diff ${{ runner.temp }}/ex03.output3.txt testingFiles/C++/ex03/CorrectOutput/ex03.correct.output3.txt
  ex04:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup g++
      run: sudo apt-get install -y g++
    - name: Compile
      run: make ex04
    - name: run test1
      run: |
        ./C++/ex04/ex04.exe < testingFiles/C++/ex04/ex04.input1.txt > ${{ runner.temp }}/ex04.output1.txt
        diff ${{ runner.temp }}/ex04.output1.txt testingFiles/C++/ex04/CorrectOutput/ex04.correct.output1.txt
    - name: run test2
      run: |
        ./C++/ex04/ex04.exe < testingFiles/C++/ex04/ex04.input2.txt > ${{ runner.temp }}/ex04.output2.txt
        diff ${{ runner.temp }}/ex04.output2.txt testingFiles/C++/ex04/CorrectOutput/ex04.correct.output2.txt
    - name: run test3
      run: |
        ./C++/ex04/ex04.exe < testingFiles/C++/ex04/ex04.input3.txt > ${{ runner.temp }}/ex04.output3.txt
        diff ${{ runner.temp }}/ex04.output3.txt testingFiles/C++/ex04/CorrectOutput/ex04.correct.output3.txt
  ex05:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup g++
      run: sudo apt-get install -y g++
    - name: Compile
      run: make ex05
    - name: run test1
      run: |
        ./C++/ex05/ex05.exe < testingFiles/C++/ex05/ex05.input1.txt > ${{ runner.temp }}/ex05.output1.txt
        diff ${{ runner.temp }}/ex05.output1.txt testingFiles/C++/ex05/CorrectOutput/ex05.correct.output1.txt
    - name: run test2
      run: |
        ./C++/ex05/ex05.exe < testingFiles/C++/ex05/ex05.input2.txt > ${{ runner.temp }}/ex05.output2.txt
        diff ${{ runner.temp }}/ex05.output2.txt testingFiles/C++/ex05/CorrectOutput/ex05.correct.output2.txt
    - name: run test3
      run: |
        ./C++/ex05/ex05.exe < testingFiles/C++/ex05/ex05.input3.txt > ${{ runner.temp }}/ex05.output3.txt
        diff ${{ runner.temp }}/ex05.output3.txt testingFiles/C++/ex05/CorrectOutput/ex05.correct.output3.txt

  ex06:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup g++
      run: sudo apt-get install -y g++
    - name: Compile
      run: make ex06
    - name: run test1
      run: |
        ./C++/ex06/ex06.exe < testingFiles/C++/ex06/ex06.input1.txt > ${{ runner.temp }}/ex06.output1.txt
        diff ${{ runner.temp }}/ex06.output1.txt testingFiles/C++/ex06/CorrectOutput/ex06.correct.output1.txt
    - name: run test2
      run: |
        ./C++/ex06/ex06.exe < testingFiles/C++/ex06/ex06.input2.txt > ${{ runner.temp }}/ex06.output2.txt
        diff ${{ runner.temp }}/ex06.output2.txt testingFiles/C++/ex06/CorrectOutput/ex06.correct.output2.txt
    - name: run test3
      run: |
        ./C++/ex06/ex06.exe < testingFiles/C++/ex06/ex06.input3.txt > ${{ runner.temp }}/ex06.output3.txt
        diff ${{ runner.temp }}/ex06.output3.txt testingFiles/C++/ex06/CorrectOutput/ex06.correct.output3.txt
  ex07:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup g++
      run: sudo apt-get install -y g++
    - name: Compile
      run: make ex07
    - name: run test1
      run: |
        ./C++/ex07/ex07.exe < testingFiles/C++/ex07/ex07.input1.txt > ${{ runner.temp }}/ex07.output1.txt
        diff ${{ runner.temp }}/ex07.output1.txt testingFiles/C++/ex07/CorrectOutput/ex07.correct.output1.txt
    - name: run test2
      run: |
        ./C++/ex07/ex07.exe < testingFiles/C++/ex07/ex07.input2.txt > ${{ runner.temp }}/ex07.output2.txt
        diff ${{ runner.temp }}/ex07.output2.txt testingFiles/C++/ex07/CorrectOutput/ex07.correct.output2.txt
    - name: run test3
      run: |
        ./C++/ex07/ex07.exe < testingFiles/C++/ex07/ex07.input3.txt > ${{ runner.temp }}/ex07.output3.txt
        diff ${{ runner.temp }}/ex07.output3.txt testingFiles/C++/ex07/CorrectOutput/ex07.correct.output3.txt