name: Copy Secret to Forked Repository

on:
  fork:

jobs:
  copy-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Secret
        env:
          MAIN_REPO_SECRET: ${{ secrets.DECRIPTION_KEY }}
        run: |
          echo "${MAIN_REPO_SECRET}" | tr -d '\n' > /tmp/secret_value
          curl -X PUT \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -d @/tmp/secret_value \
          "https://api.github.com/repos/${{ github.repository }}/actions/secrets/DECRIPTION_KEY"