name: Private Tests

on:
  push:
    branches:
      - main

jobs:
  grade:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Decrypt File
        run: |
          # Decrypt the encrypted file using OpenSSL
          openssl enc -d -aes-256-cbc -in encrypted-file.enc -out decrypted-file.txt -pass pass:${{ secrets.DECRIPTION_KEY }}
    
      - name: Display Decrypted File
        run: cat decrypted-file.txt
      - name: make
        run: make all
      - name: run file
        run: ./C++/ex01a/ex01a.exe <.io/ex01a/ex01.input.txt > .io/ex01a/ex01.output.txt
      - name: compare results
        run: diff C++/ex01a/ex01.output.txt C++/ex01a/ex01.correct.output.txt